package com.javasatu.journalistappreciator.ui.theme

import androidx.compose.ui.graphics.Color

val jaLightPrimary = Color(0xFF825500)
val jaLightOnPrimary = Color(0xFFFFFFFF)
val jaLightPrimaryContainer = Color(0xFFFFDDAE)
val jaLightOnPrimaryContainer = Color(0xFF2A1800)
val jaLightSecondary = Color(0xFF6F5B40)
val jaLightOnSecondary = Color(0xFFFFFFFF)
val jaLightSecondaryContainer = Color(0xFFFADEBC)
val jaLightOnSecondaryContainer = Color(0xFF271904)
val replyLightTertiary = Color(0xFF516440)
val replyLightOnTertiary = Color(0xFFFFFFFF)
val replyLightTertiaryContainer = Color(0xFFD3EABC)
val replyLightOnTertiaryContainer = Color(0xFF102004)
val replyLightError = Color(0xFFBA1B1B)
val replyLightErrorContainer = Color(0xFFFFDAD4)
val replyLightOnError = Color(0xFFFFFFFF)
val replyLightOnErrorContainer = Color(0xFF410001)
val replyLightBackground = Color(0xFFFCFCFC)
val replyLightOnBackground = Color(0xFF1F1B16)
val replyLightSurface = Color(0xFFFCFCFC)
val replyLightOnSurface = Color(0xFF1F1B16)
val replyLightSurfaceVariant = Color(0xFFF0E0CF)
val replyLightOnSurfaceVariant = Color(0xFF4F4539)
val replyLightOutline = Color(0xFF817567)
val replyLightInverseOnSurface = Color(0xFFF9EFE6)
val replyLightInverseSurface = Color(0xFF34302A)
val replyLightPrimaryInverse = Color(0xFFFFB945)

val jaDarkPrimary = Color(0xFFFFB945)
val jaDarkOnPrimary = Color(0xFF452B00)
val jaDarkPrimaryContainer = Color(0xFF624000)
val jaDarkOnPrimaryContainer = Color(0xFFFFDDAE)
val jaDarkSecondary = Color(0xFFDDC3A2)
val jaDarkOnSecondary = Color(0xFF3E2E16)
val jaDarkSecondaryContainer = Color(0xFF56442B)
val jaDarkOnSecondaryContainer = Color(0xFFFADEBC)
val jaDarkTertiary = Color(0xFFB8CEA2)
val jaGelapOnTertiary = Color(0xFF243516)
val jaGelapTertiaryContainer = Color(0xFF3A4C2B)
val jaGelapOnTertiaryContainer = Color(0xFFD3EABC)
val jaGelapError = Color(0xFFFFB4A9)
val jaGelapErrorContainer = Color(0xFF930006)
val jaGelapOnError = Color(0xFF680003)
val jaGelapOnErrorContainer = Color(0xFFFFDAD4)
val jaGelapDarkBackground = Color(0xFF1F1B16)
val jaGelapDarkOnBackground = Color(0xFFEAE1D9)
val jaGelapSurface = Color(0xFF1F1B16)
val jaGelapOnSurface = Color(0xFFEAE1D9)
val jaGelapSurfaceVariant = Color(0xFF4F4539)
val jaGelapOnSurfaceVariant = Color(0xFFD3C4B4)
val jaGelapOutline = Color(0xFF9C8F80)
val jaGelapInverseOnSurface = Color(0xFF32281A)
val jaGelapInverseSurface = Color(0xFFEAE1D9)
val jaGelapPrimaryInverse = Color(0xFF624000)